### ISSUE TITLE
Chromedriver version [SOLVED]

### ISSUE THREAD

**Issue by aurel2222** [smf33/FlickrFollowerBot#3]
Hi,
once again coming back to ask about a problem.

Yesterday, the bot was working very well. This morning it gives 👍 

--------------------
NewChromeSeleniumWrapper(C:\Users\AB\Documents\Follow\FlickrFollowerBot\bin\Debug\netcoreapp3.1, 1874, 1513)
Starting ChromeDriver 80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}) on port 60451
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

DevTools listening on ws://127.0.0.1:60456/devtools/browser/4828632d-ab4c-443d-a701-faca85e49202
## ENDED IN ERROR : **session not created: This version of ChromeDriver only supports Chrome version 80 (SessionNotCreated)**
System.InvalidOperationException: session not created: This version of ChromeDriver only supports Chrome version 80 (SessionNotCreated)
-----------------------------------------------------------------------

Chrome version i use is 83.
I downloaded chromedrover 83 and copied it in the bot directory :
C:\Users\AB\Documents\Follow\FlickrFollowerBot\bin\Debug\netcoreapp3.1

But is seems it is changer each time i launch the bot...

Still working on the interface but need to learn a lot...

thanks for the help !

**Comment by smf33** [comment]
Hi,
A build will erase the output folder and so set the version in the projet
setting.
So, Update the version number in the csproj file.
Else you can also use dotnet command to update this reference.

Hope it os clear enough !

**Comment by aurel2222** [comment]
Clear and efficient, it works perfectly. Thanks !

**Comment by markplus** [comment]
Hi, I have the same problem and I don't understand how to solve it

`## ENDED IN ERROR : session not created: This version of ChromeDriver only supports Chrome version 81 (SessionNotCreated)
System.InvalidOperationException: session not created: This version of ChromeDriver only supports Chrome version 81 (SessionNotCreated)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options)
   at FlickrFollowerBot.SeleniumWrapper.NewChromeSeleniumWrapper(String path, String w, String h, IEnumerable`1 seleniumBrowserArguments, Single botSeleniumTimeoutSec) in C:\FlickrFollowerBot-master\SeleniumWrapper.cs:line 35`

**Comment by smf33** [comment]
Hi,
Could you check your chrome browser major version, the major version of
ChromeDriver in the .csproj, Update the ChromeDriver version of the .csproj
(I guess) , and rebuild the project ?

**Comment by markplus** [comment]
hi.
Versione 83.0.4103.97
I don't know how to update the version, can you tell me how to do it?

**Comment by smf33** [comment]
Hi,
Could u try this to update your package ref (from the bot project
directory):
dotnet add package Selenium.WebDriver.ChromeDriver

**Comment by markplus** [comment]
thanks now it works
