### ISSUE TITLE
Timed out error

### ISSUE THREAD

**Issue by San114** [smf33/FlickrFollowerBot#5]
Hi, I'm using the unfollow those who don't follow me feature on dot net and everytime if finishes scanning my follower pages, this error pops up:

}('We\'re sorry, Flickr <a href="{faq}" target="_top">doesn\'t allow embedding within frames</a>.<br><br>If you\'d like to view this content, <a href="{url}" target="_top">please click here</a>.', 'https://www.flickr.com', true, false));

</script></head>
# Try saving Data in order to avoid queue polution
SAVING USER JSON
## ENDED IN ERROR : timeout: Timed out receiving message from renderer: 28.963
  (Session info: chrome=84.0.4147.105)
OpenQA.Selenium.WebDriverTimeoutException: timeout: Timed out receiving message from renderer: 28.963
  (Session info: chrome=84.0.4147.105)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.set_Url(String value)
   at FlickrFollowerBot.SeleniumWrapper.set_Url(String value) in C:\Users\lukas\OneDrive\Área de Trabalho\FlickrFollowerBot-master\SeleniumWrapper.cs:line 79
   at FlickrFollowerBot.FollowerBot.MoveTo(String partialOrNotUrl, Boolean forceReload) in C:\Users\lukas\OneDrive\Área de Trabalho\FlickrFollowerBot-master\FollowerBot.Actions.cs:line 69
   at FlickrFollowerBot.FollowerBot.GetContactList(String subUrl) in C:\Users\lukas\OneDrive\Área de Trabalho\FlickrFollowerBot-master\FollowerBot.Actions.cs:line 101
   at FlickrFollowerBot.FollowerBot.DetectContactsUnfollowBack() in C:\Users\lukas\OneDrive\Área de Trabalho\FlickrFollowerBot-master\FollowerBot.Actions.cs:line 522
   at FlickrFollowerBot.FollowerBot.Run() in C:\Users\lukas\OneDrive\Área de Trabalho\FlickrFollowerBot-master\FollowerBot.cs:line 121
   at FlickrFollowerBot.Program.Main(String[] args) in C:\Users\lukas\OneDrive\Área de Trabalho\FlickrFollowerBot-master\Program.cs:line 18

Could you help me please? Thank you.

**Comment by smf33** [comment]
Hi,
Well it s a common issue on Selenium, but you should not get this everytime and at this first step.

You can increase timeout (set BotSeleniumTimeoutSec at 60 in FlickrFollowerBot.json or command line switch or env setting)
You can also try to optimise chrome with SeleniumBrowserArguments in the same file (add --headless in the string with a | before or after this new switch)

But mainly, if you have constant timeout at these first step, it seems you have execution performance issue.
Could you give more info on the execution context ?
Did it work before ? How are you running the bot ?
Are you running the contener version ? 
Do you run on a normal computer or limited cpu/ram (virtual) host ?
Do you run on windows or linux ?

Hope it help.
But for info, my bots have some tweack all the bot settings; the SeleniumBrowserArguments is the main on in order to optimise the bot on virtual env with limited ressources.

**Comment by San114** [comment]
Thank you! It really fixed my issue.

I'm just having another thing, now when it starts unfollowing people, after if unfollows around 30-40 people, the bot exits with code 0.

Do you know why or what's happening? I have up to 2k accounts to unfollow.
Also I wondered if there's a way to just unfollow everyone instead of those who don't follow back?

Sorry importunating you with all these questions, your bot is GREAT and these tasks will make wonders for me!

**Comment by smf33** [comment]
Hi,
In short, the bot is highly tweackeable and allow some randomness in order
to avoid been detected as bot and maybe ban (usualy you have a warning and
are block some time before than). Default settings should allow one or two
daily run without issue.

But You can add a « loop » as last action (there is also a limit setting
here) or change the unfollowing min/max value in setting. Unfollowing 2k
people once may work , but up to you to take the risk :-)

You can force the unfollow by adding theses guy manually with a setting
used for theses actions. Or maybe easier if you have a lot, edit your
session file by removing the array of your current followed guy. I can
detail a little more depending of how many guy in this case
