### ISSUE TITLE
unknown error: net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by thibautflottat** [smf33/FlickrFollowerBot#7]
Hi ! 
First of all, thank you for this fantastic tool.

I mainly use it with those settings : dotnet run BotTasks=DetectExplored,DoPhotosFav,DoContactsFollow ; but the same occurs using dotnet run.

It likes and follow more or less 30 objects, and then it crashes with this error :

`## ENDED IN ERROR : unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=87.0.4280.66)
OpenQA.Selenium.WebDriverException: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=87.0.4280.66)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary 2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.set_Url(String value)
   at FlickrFollowerBot.SeleniumWrapper.set_Url(String value) in /home/thibaut/web/FlickrFollowerBot-master/SeleniumWrapper.cs:line 79
   at FlickrFollowerBot.FollowerBot.MoveTo(String partialOrNotUrl, Boolean forceReload) in /home/thibaut/web/FlickrFollowerBot-master/FollowerBot.Actions.cs:line 69
   at FlickrFollowerBot.FollowerBot.DoContactsFollow() in /home/thibaut/web/FlickrFollowerBot-master/FollowerBot.Actions.cs:line 368
   at FlickrFollowerBot.FollowerBot.Run() in /home/thibaut/web/FlickrFollowerBot-master/FollowerBot.cs:line 112
   at FlickrFollowerBot.Program.Main(String[] args) in /home/thibaut/web/FlickrFollowerBot-master/Program.cs:line 18
`

The chromewebdriver is 86.0.4240.2200 in the csproj file, maybe it is related as I am using Chromium 87. So I tried to update to ChromeDriver 87.0.4280.20 (using dotnet add package Selenium.WebDriver.ChromeDriver), but nothing changes.

Thank you !

**Comment by smf33** [comment]
Hi,
Yeah strange, this look like an issue between your bot and the selenium server.
Could you provide more information on the context exec ? 
- Do you use an selenium server  ????? 
- Maybe provide a litlle more information on the previous log
- Was it working previously ?
Updating the Chrome Driver (Selenium.WebDriver.ChromeDriver) is require only if you use a local chrome (no selenium server so), you seem use a "remove" selenium server in your trace, but it may be a misconfiguration maybe? Have you set a SeleniumRemoteServer ?
Hope it will help !

**Comment by thibautflottat** [comment]
I was using chromium on linux. I installed chrome instead, and now it is working flawlessly !

**Comment by smf33** [comment]
Yes, it s strict true Chrome only. I will add this in the readme with the
version warning.
Have fun !
